# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymarchome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetables',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
