# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ymarchome', '0003_nonvef'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NonVef',
            new_name='NonVeg',
        ),
    ]
